### ISSUE TITLE
fog

### ISSUE THREAD

**Issue by daraleak** [oxiKKK/oxware#11]
void Oxwa::Fog::Draw()
{
	if (!cvar.visual_fog)
		return;
	
	if (!Oxwa::ScreenShot::IsVisuals())
		return;

	GLfloat glColor[] = { cvar.visual_fog_color[0], cvar.visual_fog_color[1], cvar.visual_fog_color[2], cvar.visual_fog_color[3] };
	glEnable(GL_FOG);
	glFogi(GL_FOG_MODE, GL_EXP);
	glFogf(GL_FOG_DENSITY, cvar.visual_fog_density / 10000.f);
	glFogfv(GL_FOG_COLOR, glColor);

shitpasted but i think you are understand what needs

**Comment by oxiKKK** [comment]
Gotcha. I will implement this.

**Comment by oxiKKK** [comment]
Implemented in [d39fdee](https://github.com/oxiKKK/oxware/commit/d39fdee8c1690e7a9d51ddbd6417b2929e59f883).

![image](https://github.com/oxiKKK/oxware/assets/28988905/a387cf34-a44c-4507-ada9-e7e5774d1b9e)
