### ISSUE TITLE
about render 

### ISSUE THREAD

**Issue by daraleak** [oxiKKK/oxware#21]
make the render more flexible (if possible) changing the size of the render object, etc(this is what I meant about a game render such as velocity and kz info)

about the rendering of the gui and the menu, I can say that it would be nice to customize the render (also if possible)

**Comment by oxiKKK** [comment]
Hi

Yes, in the future release I plan to implement both themes https://github.com/oxiKKK/oxware/issues/10 and this https://github.com/oxiKKK/oxware/issues/7. I can do the same with the kz visuals.

**Comment by daraleak** [comment]
> Hi
> 
> Yes, in the future release I plan to implement both themes #10 and this #7. I can do the same with the kz visuals.

I also wanted to ask what will happen when you finish your project for 1.6 or 1.6 you get bored, will you do oxware but for counter strike source?

**Comment by daraleak** [comment]
it's very cool that you're working on your project, while coders like xvi and killabeez just got drunk and scored on their project

**Comment by daraleak** [comment]
> Well, first of all I will finish this project by implementing all of the "harder" goals such as:
> 
>     * Implementing as much features as possible (aimbot, trigger, knifebot, waybot, and all of these, texture/model changer, lua scripting, and many many more features)
> 
>     * making the cheat cross-platform (for osx and linux)
> 
>     * making the cheat stable and crash-free
> 
>     * etc.
> 
> 
> Then I will not make any other cheats for this game, as this is my definitive creation :) Perhaps, I will move to another game, I don't know that for now. For now, the goal is to continue working on this cheat and to continue pushing changes and improvements.

it's very cool that you're working on your project, while coders like xvi and killabeez just got drunk and scored on their project

**Comment by daraleak** [comment]
> Well, first of all I will finish this project by implementing all of the "harder" goals such as:
> 
>     * Implementing as much features as possible (aimbot, trigger, knifebot, waybot, and all of these, texture/model changer, lua scripting, and many many more features)
> 
>     * making the cheat cross-platform (for osx and linux)
> 
>     * making the cheat stable and crash-free
> 
>     * etc.
> 
> 
> Then I will not make any other cheats for this game, as this is my definitive creation :) Perhaps, I will move to another game, I don't know that for now. For now, the goal is to continue working on this cheat and to continue pushing changes and improvements.

I would also like to ask about the edgebug that is in the cheat at the moment, does it work like every else or otherwise?

**Comment by oxiKKK** [comment]
The edgebug should work like every other edgebug out there. With a few customizations. 

- **intensity**: you can use intensity to control the chance of hitting the edgebug.
- **fallvelocity**: edgebug helper will activate only when you have exceeded this velocity.
- **edge dist**: same as fallvelocity, but with the edge distance.
- **ground dist**: same as fallvelocity, but with ground distance.

**Comment by daraleak** [comment]
> The edgebug should work like every other edgebug out there. With a few customizations.
> 
>     * **intensity**: you can use intensity to control the chance of hitting the edgebug.
> 
>     * **fallvelocity**: edgebug helper will activate only when you have exceeded this velocity.
> 
>     * **edge dist**: same as fallvelocity, but with the edge distance.
> 
>     * **ground dist**: same as fallvelocity, but with ground distance.

ok thanks i understood

**Comment by daraleak** [comment]
@oxiKKK  can you add me in discord my nickname awallsystem
