### ISSUE TITLE
Please update the cheat to (somehow) work on 25-th anniversary of Half-Life version of CS 1.6

### ISSUE THREAD

**Issue by Yaroslaw007** [oxiKKK/oxware#37]
I hope you dont have a stroke while reading the title of the bug;
The cheat keeps on bringing up the error saying that the build engine is not supported, and when you press OK, it just keeps on appearing and appearing until you end task of the Half-Life Launcher application in task manager.

https://github.com/oxiKKK/oxware/assets/84519059/2bee1b6d-e718-47c4-a0c3-cedcc28b7280

Please fix this (if even possible).

**Comment by syedaliaun352** [comment]
+1 this one will be big

**Comment by Yaroslaw007** [comment]
> just change ur game ver to legacy

earlier i just had a problem where i had a low-end laptop which wasnt working quite well at the legacy version... right now i have upgraded 6 months ago xd
