### ISSUE TITLE
OpenGL

### ISSUE THREAD

**Issue by Iamisrohmat** [oxiKKK/oxware#39]
**hey can you modify this program? i got error 

GLFW error occured:
requested OpenGL version 3,0, got version 2.1** 
![Uploading Capture.jpg…]()

**Comment by Iamisrohmat** [comment]
![Capture](https://github.com/oxiKKK/oxware/assets/97291287/7fa95ce5-cb1a-424e-8ec4-faec9d249c7b)

**Comment by yarik303** [comment]
i know a solution.. i think it means that ur gpu cant do opengl 3.0 
there is a work around by installing mesa3d drivers (not cheat)
https://github.com/pal1000/mesa-dist-win
release -> and install msvc version


or just get a better gpu lol


also activate windows god dam it
