### ISSUE TITLE
aspect ratio

### ISSUE THREAD

**Issue by daraleak** [oxiKKK/oxware#4]
add aspect ratio

**Comment by oxiKKK** [comment]
Hi. Thanks for suggestion.

I did some research, and this can be done even in GoldSrc by modifying the code. (In Source there's a r_aspectratio cvar for the same thing). I will implement this soon.

### How to accomplish:
Modify **MYgluPerspective**'s parameter _aspect_ to whatever aspect ratio you want.

**Comment by oxiKKK** [comment]
Implemented in [7560cb2](https://github.com/oxiKKK/oxware/commit/7560cb27f29ba4b3e449091aef3d3cbf4828b865).
