### ISSUE TITLE
[bug] error when injecting

### ISSUE THREAD

**Issue by Child-dll** [oxiKKK/oxware#40]
![Captura](https://github.com/oxiKKK/oxware/assets/163706344/fd91cc3f-5ec7-4289-b2df-6609bb38f4a3)

when i try to inject the cheat i get this error, i can use the cheat but when i try to use some features like player list the game crashes, also i cant use the ESP although i have a compatible version (no-steam 3266)

**Comment by oxiKKK** [comment]
The game updated and the cheat is no longer up to date with the newest HL25 update.
