### ISSUE TITLE
[WGScan] Hidden files in PC...

### ISSUE THREAD

**Issue by tebrex98** [oxiKKK/oxware#42]
After testing on Non-Steam I deleted it from the computer and after a couple of days when I ran WGScan on my Steam account, WG Scan marked me as "Found Oxware Data", which means that somewhere this program recorded some registry. Big zero for this cheat even though I just downloaded it to test it on my server. Next time make the installation so that clients can run Uninstall.exe to delete all files and registries.

- amx

https://www.wargods.ro/wcd/report.php?id=2885037

**Comment by UnrealKaraulov** [comment]
![image](https://github.com/oxiKKK/oxware/assets/88730285/0071da41-e652-40f1-9654-43e6852086ac)

**Comment by oxiKKK** [comment]
Yes, I was planning to implement a feature that would mitigate that findage. 

BTW: there's a section for uninstalling in the README section.
